version: '3'

services:
  api:
    build: sr_api/
    image: pvayda/sr_api
    depends_on:
      - 'database'
    ports: 
      - '3001:3001'
    volumes:
      - ./sr_api:/src/app
  

  client:
    build: sr_client3/
    image: pvayda/sr_client3
    depends_on:
      - 'database'
    ports:
      - '3005:3005'
    volumes:
      - ./sr_client3:/src/app

  database:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=service_requests
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./sr_db/init.sql:/docker-entrypoint-initdb.d/init.sql